apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "chart.fullname" . }}-hpa-oda-dda-passive
  labels:
{{ include "chart.labels" . | indent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: oda-dda-passive
  minReplicas: 1
  maxReplicas: 30
  metrics:
  - type: External
    external:
      metric:
        name: oda_dqueue_public
        #selector:
        #  matchLabels:
        #    queue: "worker_tasks"
      target:
        type: Value
        value: 10m
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
      - type: Percent
        value: 100
        periodSeconds: 15
    scaleUp:
      stabilizationWindowSeconds: 5
      policies:
      - type: Percent
        value: 200
        periodSeconds: 5
      - type: Pods
        value: 4
        periodSeconds: 5
      selectPolicy: Max
